services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
      - .env:/var/www/html/.env
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpqa:
    image: jakzal/phpqa:latest
    container_name: phpqa
    working_dir: /app
    volumes:
      - ./app:/var/www/html

  phpunit:
    image: php:8.3-cli
    container_name: phpunit
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["./vendor/bin/phpunit"]

volumes:
  mysql_data:
